let accounts = [], currentFilter = 'all', poolFilter = 'all', editingID = null, discoveredKeys = [], discoveryComplete = false, loginExtractionComplete = false, modelCatalog = { go: { models: [], error: '' }, zen: { models: [], error: '' } }, activeModelType = 'go';
const $ = s => document.querySelector(s), $$ = s => document.querySelectorAll(s);
const windows = a => [a.rolling, a.weekly, a.monthly].filter(Boolean);
const maxUsage = a => windows(a).length ? Math.max(...windows(a).map(x => x.usagePercent)) : 0;
const statusText = s => s === 'healthy' ? '运行正常' : s === 'warning' ? '接近阈值' : s === 'critical' ? '用量告急' : s === 'checking' ? '检查中' : '连接失败';
const statusClass = s => ['warning', 'critical', 'error'].includes(s) ? s : 'healthy';
const formatTime = v => v && !v.startsWith('0001-') ? new Date(v).toLocaleString('zh-CN', { month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit' }) : '尚未检查';
const formatDuration = value => { const ms = Math.max(0, Number(value) || 0); if (ms < 1000) return `${Math.round(ms)} ms`; if (ms < 60000) return `${(ms / 1000).toFixed(ms < 10000 ? 1 : 0)} 秒`; const minutes = Math.floor(ms / 60000), seconds = Math.floor((ms % 60000) / 1000); return `${minutes} 分 ${String(seconds).padStart(2, '0')} 秒`; };
const resetText = w => { if (!w) return '无数据'; const sec = Math.max(0, Math.round((new Date(w.resetAt) - Date.now()) / 1000)); if (sec < 60) return '即将重置'; if (sec < 3600) return `${Math.ceil(sec / 60)} 分钟后重置`; if (sec < 86400) return `${Math.ceil(sec / 3600)} 小时后重置`; return `${Math.ceil(sec / 86400)} 天后重置`; };
const money = v => '$' + Number(v || 0).toFixed(2);
const accountTypeBadges = a => a.type === 'go_zen' ? '<i class="provider-badge">GO</i><i class="provider-badge zen">ZEN</i>' : a.type === 'go' ? '<i class="provider-badge">GO</i>' : a.type === 'zen' ? '<i class="provider-badge zen">ZEN</i>' : '<i class="provider-badge free">FREE</i>';

async function api(url, options) { const res = await fetch(url, options); if (res.status === 401) { const next = location.pathname + location.hash; location.assign('/login?expired=1&next=' + encodeURIComponent(next)); throw new Error('管理登录已失效，正在返回登录页'); } if (!res.ok) { let data = {}; try { data = await res.json(); } catch {} throw new Error(data.error || `HTTP ${res.status}`); } if (res.status === 204) return null; return res.json(); }
async function load() { accounts = await api('/api/accounts'); render(); }
async function loadVersion() { try { const info = await api('/api/version'); $('#app-version').textContent = `OpenCode Pool Gateway ${info.version}`; } catch {} }
async function loadAuthProfile() { try { const profile = await api('/api/auth'); $('#login-username').value = profile.username || ''; } catch (e) { toast(e.message); } }

function render() {
  const goCount = accounts.filter(a => a.goAvailable).length, zenCount = accounts.filter(a => a.zenBillingEnabled).length;
  $('#total').textContent = accounts.length; $('#type-summary').textContent = `Go ${goCount} · Zen ${zenCount}`;
  $('#healthy').textContent = accounts.filter(a => a.status === 'healthy').length;
  $('#attention').textContent = accounts.filter(a => !['healthy', 'checking'].includes(a.status)).length;
  $('#zen-cost').textContent = money(accounts.filter(a => a.zenBillingEnabled).reduce((s, a) => s + (a.zenBalance || 0), 0));
  renderOverview(); renderAlerts(); renderPool($('#account-search').value);
}

function usageCard(label, w) { if (!w) return `<div class="usage-window unavailable"><div class="model-line"><span>${label}</span><b>无数据</b></div><div class="bar"></div><small>等待官方数据</small></div>`; const p = Math.round(w.usagePercent); return `<div class="usage-window"><div class="model-line"><span>${label} · $${w.limitUsd}</span><b>${p}%</b></div><div class="bar"><div class="fill ${p >= 90 ? 'danger' : p >= 80 ? 'warn' : ''}" style="width:${Math.min(100, p)}%"></div></div><small>${resetText(w)}</small></div>`; }
function goDetails(a) { return `<div class="models">${usageCard('5 小时', a.rolling)}${usageCard('每周', a.weekly)}${usageCard('每月', a.monthly)}</div>`; }
function zenDetails(a) { if (!a.zenAvailable) return `<div class="account-error service-note">Zen 页面未检测到：${escapeHTML(a.zenError || '暂无数据')}</div>`; if (!a.zenBillingEnabled) return '<div class="service-note free-note">Free 账号，未开启 Zen 按量计费</div>'; return `<div class="zen-metrics"><div class="zen-metric"><span>Zen 当前余额</span><b>${money(a.zenBalance)}</b></div><div class="zen-metric"><span>计费方式</span><b>按量付费</b></div><div class="zen-metric"><span>状态</span><b>${a.zenBalance > 0 ? '可用' : '余额为零'}</b></div></div>`; }

function renderOverview() {
  const list = accounts.filter(a => currentFilter === 'all' || (currentFilter === 'warning' && ['warning', 'critical'].includes(a.status)) || (currentFilter === 'error' && a.status === 'error'));
  $('#account-list').innerHTML = list.length ? list.map(a => `<div class="account"><div class="account-top"><div class="account-id"><span class="avatar">${a.name.slice(0, 1)}</span><div><div class="account-name">${escapeHTML(a.name)}${accountTypeBadges(a)}</div><div class="account-email">${escapeHTML(a.workspaceId || '仅 API Key')} · ${a.modelCount || 0} 个模型</div></div></div><div class="status ${statusClass(a.status)}"><i class="dot"></i>${statusText(a.status)}</div></div>${a.error ? `<div class="account-error">${escapeHTML(a.error)}</div>` : ''}<div class="service-title">Go 订阅</div>${a.goAvailable ? goDetails(a) : `<div class="account-error service-note">Go 未开通或无额度窗口</div>`}<div class="service-title">Zen 按量付费</div>${zenDetails(a)}<div class="checked">检查于 ${formatTime(a.lastChecked)}</div></div>`).join('') : '<div class="empty">还没有工作区，添加一次即可自动检测 Go 与 Zen。</div>';
}

function renderAlerts() { const list = accounts.filter(a => ['warning', 'critical', 'error'].includes(a.status)); $('#alert-count').textContent = list.length; $('#alert-list').innerHTML = list.length ? list.map(a => `<div class="alert"><span class="alert-icon ${a.status === 'error' || a.status === 'critical' ? 'red' : ''}">${a.status === 'error' ? '!' : '↗'}</span><div><b>${escapeHTML(a.name)} · ${statusText(a.status)}</b><p>${a.error ? escapeHTML(a.error) : a.goAvailable ? `Go 最高窗口已使用 ${Math.round(maxUsage(a))}%` : `Zen 当前余额 ${money(a.zenBalance)}`}</p><time>${formatTime(a.lastChecked)}</time></div></div>`).join('') : '<div class="empty">暂无真实告警</div>'; }

function quotaMini(label, value, unavailableText = '未开通') { if (!value) return `<div class="quota-mini muted-quota"><span>${label}</span><b>${unavailableText}</b><i></i></div>`; const p = Math.round(value.usagePercent); return `<div class="quota-mini"><span>${label}</span><b>${p}%</b><i><i class="${p >= 90 ? 'danger' : p >= 80 ? 'warn' : ''}" style="width:${Math.min(100, p)}%"></i></i><small>${resetText(value)}</small></div>`; }
function renderPool(q = '') {
  q = q.trim().toLowerCase();
  const list = accounts.filter(a => (!q || a.name.toLowerCase().includes(q) || (a.workspaceId || '').toLowerCase().includes(q)) && (poolFilter === 'all' || (poolFilter === 'healthy' && a.status === 'healthy') || (poolFilter === 'attention' && ['warning', 'critical'].includes(a.status)) || (poolFilter === 'error' && a.status === 'error')));
  $('#pool-count').textContent = `${list.length} 个工作区`;
  $('#pool-list').innerHTML = list.length ? list.map(a => { const quotaUnavailable = a.apiOnly ? '需 Cookie' : '未开通'; const goState = a.apiOnly ? (a.goAvailable ? '已探测可用' : '权益未确认') : (a.goAvailable ? `最高 ${Math.round(maxUsage(a))}%` : '未开通'); return `<article class="pool-card ${statusClass(a.status)}"><div class="pool-card-head"><div class="account-id"><span class="pool-avatar">${a.name.slice(0, 1)}</span><div class="pool-identity"><div class="pool-card-name" title="${escapeHTML(a.name)}">${escapeHTML(a.name)}</div><div class="pool-workspace" title="${escapeHTML(a.workspaceId || '仅 API Key')}">${escapeHTML(a.workspaceId || '仅 API Key')}</div></div></div><span class="pool-status ${statusClass(a.status)}"><i></i>${statusText(a.status)}</span></div><div class="pool-health"><span class="pool-account-type">${accountTypeBadges(a)}</span><span>Cookie ${a.hasCookie ? '已配置' : a.apiOnly ? '不适用' : '缺失'}</span><span>API Key ${a.hasApiKey ? '已获取' : '未配置'}</span><span>Go ${a.goModelCount || 0} · Zen ${a.zenModelCount || 0}</span><time>${formatTime(a.lastChecked)}</time></div>${a.error ? `<div class="account-error">${escapeHTML(a.error)}</div>` : ''}<div class="pool-service"><div class="pool-service-title"><span>Go 订阅额度</span><em>${goState}</em></div><div class="quota-mini-grid">${quotaMini('5 小时', a.rolling, quotaUnavailable)}${quotaMini('每周', a.weekly, quotaUnavailable)}${quotaMini('每月', a.monthly, quotaUnavailable)}</div>${a.apiOnly ? '<div class="quota-read-note">仅 API Key 无法读取 Go 配额窗口，需配置 Workspace Cookie</div>' : ''}</div><div class="pool-service zen-service"><div class="pool-service-title"><span>Zen 按量付费</span><em>${a.zenBillingEnabled ? '已开启' : a.zenAvailable ? 'Free' : '未识别'}</em></div><div class="zen-balance-row"><span>当前余额</span><b>${a.zenBillingEnabled ? money(a.zenBalance) : '—'}</b></div></div><footer class="pool-card-actions"><button class="models-button" data-models="${a.id}">模型</button><button title="立即刷新" data-card-refresh="${a.id}">↻</button><button class="edit-button" data-edit="${a.id}">编辑</button><button class="delete-button" title="删除工作区" data-delete="${a.id}">删除</button></footer></article>`; }).join('') : '<div class="empty pool-empty">没有匹配的工作区</div>';
  $$('[data-models]').forEach(b => b.onclick = () => openModels(b.dataset.models, b));
  $$('[data-card-refresh]').forEach(b => b.onclick = () => refreshOne(b.dataset.cardRefresh, b));
  $$('[data-edit]').forEach(b => b.onclick = () => openEdit(b.dataset.edit));
  $$('[data-delete]').forEach(b => b.onclick = () => deleteAccount(b.dataset.delete));
}

function escapeHTML(s) { const d = document.createElement('div'); d.textContent = s || ''; return d.innerHTML; }
function toast(m) { const e = $('#toast'); e.textContent = m; e.classList.add('show'); setTimeout(() => e.classList.remove('show'), 2400); }
function openView(n) { $$('.nav-item').forEach(x => x.classList.toggle('active', x.dataset.view === n)); $$('.view').forEach(x => x.classList.toggle('active', x.id === `view-${n}`)); location.hash = n; if (n === 'settings') loadAuthProfile(); scrollTo({ top: 0, behavior: 'smooth' }); }
async function refresh(button) { button.textContent = '…'; button.disabled = true; try { accounts = await api('/api/refresh', { method: 'POST' }); render(); $('#sync-time').textContent = '刚刚'; toast('Go 与 Zen 数据已分别刷新'); } catch (e) { toast(e.message); } finally { button.textContent = '↻'; button.disabled = false; } }
async function deleteAccount(id) { if (!confirm('确认删除这个监控项？本机保存的凭证也会被删除。')) return; try { await api('/api/accounts/' + encodeURIComponent(id), { method: 'DELETE' }); await load(); toast('监控项已删除'); } catch (e) { toast(e.message); } }
async function refreshOne(id, button) { button.disabled = true; button.textContent = '…'; try { const updated = await api(`/api/accounts/${encodeURIComponent(id)}/refresh`, { method: 'POST' }); const index = accounts.findIndex(a => a.id === id); if (index >= 0) accounts[index] = updated; render(); toast('工作区已刷新'); } catch (e) { toast(e.message); } finally { button.disabled = false; button.textContent = '↻'; } }
function renderModels(q = '') { q = q.trim().toLowerCase(); const group = modelCatalog[activeModelType] || { models: [], error: '' }; if (group.error) { $('#model-list').innerHTML = `<div class="account-error">${escapeHTML(group.error)}</div>`; return; } const list = (group.models || []).filter(m => !q || m.name.toLowerCase().includes(q) || m.id.toLowerCase().includes(q) || (m.provider || '').toLowerCase().includes(q) || (m.deprecated && ('已弃用'.includes(q) || 'deprecated'.includes(q)))); $('#model-list').innerHTML = list.length ? list.map(m => `<div class="model-item ${m.deprecated ? 'deprecated-model' : ''}${m.available === false ? ' unavailable-model' : ''}"><div><div class="model-name-line"><b>${escapeHTML(m.name)}</b>${m.deprecated ? '<strong>已弃用</strong>' : ''}${m.available === false ? '<strong class="access-denied">不可用</strong>' : '<strong class="access-ok">可用</strong>'}</div><code>${escapeHTML(m.id)}</code>${m.deprecated ? `<small>弃用日期：${escapeHTML(m.deprecationDate)}</small>` : ''}${m.available === false ? `<small class="unavailable-reason">${escapeHTML(m.unavailableReason || '当前凭证不可用')}</small>` : ''}</div>${m.provider ? `<span>${escapeHTML(m.provider)}</span>` : ''}</div>`).join('') : '<div class="empty">当前分类没有匹配的模型</div>'; }
function selectModelType(type) { activeModelType = type; $$('[data-model-type]').forEach(b => b.classList.toggle('active', b.dataset.modelType === type)); $('#model-search').value = ''; renderModels(); }
async function openModels(id, button) { const account = accounts.find(a => a.id === id); modelCatalog = { go: { models: [], error: '' }, zen: { models: [], error: '' } }; activeModelType = 'go'; $('#model-title').textContent = `${account ? account.name : '账号'} · 可用模型`; $('#model-description').textContent = '正在分别查询 Go 与 Zen 官方模型目录…'; $('#go-model-count').textContent = '—'; $('#zen-model-count').textContent = '—'; $('#model-search').value = ''; $('#model-list').innerHTML = '<div class="model-loading">正在查询…</div>'; $$('[data-model-type]').forEach(b => b.classList.toggle('active', b.dataset.modelType === 'go')); $('#model-modal').classList.add('open'); button.disabled = true; try { const data = await api(`/api/accounts/${encodeURIComponent(id)}/models`); modelCatalog = { go: data.go || { models: [], error: '' }, zen: data.zen || { models: [], error: '' } }; const deprecatedCount = (modelCatalog.zen.models || []).filter(m => m.deprecated).length; $('#go-model-count').textContent = (modelCatalog.go.models || []).length; $('#zen-model-count').textContent = `${(modelCatalog.zen.models || []).length}${deprecatedCount ? ` / ${deprecatedCount} 弃用` : ''}`; $('#model-description').textContent = data.authenticated ? '已使用当前 API Key 分别查询两个官方目录' : '未配置 API Key，分别显示两个公开目录'; renderModels(); } catch (e) { $('#model-description').textContent = '查询失败'; $('#model-list').innerHTML = `<div class="account-error">${escapeHTML(e.message)}</div>`; } finally { button.disabled = false; } }
function resetDiscovery() { discoveredKeys = []; discoveryComplete = false; loginExtractionComplete = false; $('#discovery-result').className = 'discovery-result'; $('#discovery-result').innerHTML = ''; }
function openAdd() { editingID = null; resetDiscovery(); $('#modal-title').textContent = '添加工作区'; $('#modal-description').textContent = '填写 Workspace ID 和 Cookie，程序会自动读取邮箱与 API Key。'; $('#api-key-hint').textContent = '可选，留空自动获取'; $('#cookie-hint').textContent = '用于自动识别账号和额度'; ['#name', '#workspace-id', '#api-key', '#auth-cookie'].forEach(x => $(x).value = ''); $('#save').textContent = '自动识别账号'; $('#modal').classList.add('open'); }
function openEdit(id) { const a = accounts.find(x => x.id === id); if (!a) return; editingID = id; resetDiscovery(); discoveryComplete = true; $('#modal-title').textContent = '编辑工作区'; $('#modal-description').textContent = '可直接保存；填写新 Cookie 后也可重新自动识别。'; $('#name').value = a.name; $('#workspace-id').value = a.workspaceId; $('#api-key').value = ''; $('#auth-cookie').value = ''; $('#api-key-hint').textContent = a.hasApiKey ? '留空则保留当前 Key' : '尚未配置，可自动获取或手动填写'; $('#cookie-hint').textContent = a.hasCookie ? '留空则保留当前 Cookie' : ''; $('#save').textContent = '保存并重新检测'; $('#modal').classList.add('open'); }
function renderDiscovery(data) { discoveredKeys = data.apiKeys || []; const box = $('#discovery-result'); const warnings = (data.warnings || []).map(x => `<p class="discovery-warning">${escapeHTML(x)}</p>`).join(''); let keys = ''; if (discoveredKeys.length) { keys = `<div class="key-options">${discoveredKeys.map((k, i) => `<label class="key-option"><input type="radio" name="discovered-key" value="${i}" ${i === 0 ? 'checked' : ''}><span><b>${escapeHTML(k.name || 'API Key')}${k.email ? ` · ${escapeHTML(k.email)}` : ''}</b><small>${escapeHTML(k.display)}</small></span></label>`).join('')}</div>`; } box.innerHTML = `<strong>${data.email ? `已识别账号：${escapeHTML(data.email)}` : '账号识别完成'}</strong><p>${discoveredKeys.length ? `找到 ${discoveredKeys.length} 个本人拥有的 API Key${discoveredKeys.length > 1 ? '，请选择本次使用的 Key' : '，已自动选择'}` : '没有可选择的 API Key，可留空保存'}</p>${keys}${warnings}`; box.className = 'discovery-result show'; }
$$('.nav-item').forEach(x => x.onclick = () => openView(x.dataset.view)); $$('.add-btn').forEach(x => x.onclick = openAdd); $$('.refresh-btn').forEach(x => x.onclick = () => refresh(x));
$$('.filter').forEach(x => x.onclick = () => { $$('.filter').forEach(y => y.classList.remove('active')); x.classList.add('active'); currentFilter = x.dataset.filter; renderOverview(); });
$('#account-search').oninput = e => renderPool(e.target.value); $('#close').onclick = $('#cancel').onclick = () => $('#modal').classList.remove('open'); $('#modal').onclick = e => { if (e.target.id === 'modal') $('#modal').classList.remove('open'); };
['#workspace-id', '#auth-cookie'].forEach(selector => $(selector).addEventListener('input', () => { if (!editingID && discoveryComplete) { resetDiscovery(); $('#save').textContent = '自动识别账号'; } }));
$('#model-search').oninput = e => renderModels(e.target.value); $('#model-close').onclick = () => $('#model-modal').classList.remove('open'); $('#model-modal').onclick = e => { if (e.target.id === 'model-modal') $('#model-modal').classList.remove('open'); };
$$('[data-model-type]').forEach(b => b.onclick = () => selectModelType(b.dataset.modelType));
$$('[data-pool-filter]').forEach(b => b.onclick = () => { $$('[data-pool-filter]').forEach(x => x.classList.remove('active')); b.classList.add('active'); poolFilter = b.dataset.poolFilter; renderPool($('#account-search').value); });
$('#save').onclick = async () => { const button = $('#save'); const payload = { Name: $('#name').value.trim(), WorkspaceID: $('#workspace-id').value.trim(), APIKey: $('#api-key').value.trim(), AuthCookie: $('#auth-cookie').value.trim() }; if (!payload.WorkspaceID || (!editingID && !payload.AuthCookie)) { toast(editingID ? '请填写 Workspace ID' : '请填写 Workspace ID 和 auth Cookie'); return; } button.disabled = true; try { if (!editingID && !discoveryComplete && !payload.Name && !payload.APIKey) { button.textContent = '正在自动识别…'; try { const data = await api('/api/accounts/discover', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ WorkspaceID: payload.WorkspaceID, AuthCookie: payload.AuthCookie }) }); if (data.email) $('#name').value = data.email; renderDiscovery(data); discoveryComplete = true; button.textContent = '确认并保存'; } catch (e) { $('#discovery-result').className = 'discovery-result show'; $('#discovery-result').innerHTML = `<strong>自动识别失败，尚未保存</strong><p class="discovery-warning">${escapeHTML(e.message)}</p><p>请检查 Workspace ID 和完整 Cookie 后重试；也可以手动填写显示名称或 API Key 后保存。</p>`; toast(e.message); button.textContent = '重新自动识别'; } return; } const selected = document.querySelector('input[name="discovered-key"]:checked'); if (!payload.APIKey && selected) payload.APIKey = discoveredKeys[Number(selected.value)].key; button.textContent = '正在重新检测…'; const url = editingID ? '/api/accounts/' + encodeURIComponent(editingID) : '/api/accounts'; const saved = await api(url, { method: editingID ? 'PUT' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); $('#modal').classList.remove('open'); editingID = null; await load(); toast(saved.status === 'error' ? `已保存，但采集失败：${saved.error}` : `工作区已保存${saved.hasApiKey ? '，API Key 已配置' : '，未配置 API Key'}`); } catch (e) { toast(e.message); } finally { button.disabled = false; button.textContent = editingID ? '保存并重新检测' : (discoveryComplete ? '确认并保存' : '自动识别账号'); } };
['warn', 'danger'].forEach(n => { $(`#${n}-range`).oninput = e => $(`#${n}-value`).textContent = e.target.value + '%'; }); $$('.save-button').forEach(x => x.onclick = () => toast('设置已保存'));
$('#save-credentials').onclick = async () => { const button = $('#save-credentials'); const username = $('#login-username').value.trim(), currentPassword = $('#current-login-password').value, newPassword = $('#new-login-password').value, confirmation = $('#confirm-login-password').value; if (!username || !currentPassword || !newPassword) { toast('请填写用户名、当前密码和新密码'); return; } if (newPassword.length < 8) { toast('新密码至少需要 8 个字符'); return; } if (newPassword !== confirmation) { toast('两次输入的新密码不一致'); return; } button.disabled = true; button.textContent = '正在更新…'; try { await api('/api/auth', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ username, currentPassword, newPassword }) }); location.assign('/login?changed=1'); } catch (e) { toast(e.message); button.disabled = false; button.textContent = '更新登录凭证'; } };
$('#shutdown').onclick = () => $('#confirm').classList.add('open'); $('#shutdown-cancel').onclick = () => $('#confirm').classList.remove('open'); $('#confirm').onclick = e => { if (e.target.id === 'confirm') $('#confirm').classList.remove('open'); }; $('#shutdown-confirm').onclick = async () => { const b = $('#shutdown-confirm'); b.textContent = '正在退出…'; b.disabled = true; try { await fetch('/api/shutdown', { method: 'POST' }); document.body.innerHTML = '<main class="stopped"><div><span class="brand-mark">G</span><h1>OpenCode Pool Gateway 已退出</h1><p>本地监控服务已安全关闭。</p></div></main>'; } catch { toast('请在控制台输入 Q 退出'); } };
// Gateway management UI and account scheduling fields.
const apiFetch = window.fetch.bind(window);
window.fetch = (url, options = {}) => {
  if ((url === '/api/accounts' || String(url).startsWith('/api/accounts/')) && ['POST', 'PUT'].includes(options.method) && options.body) {
    try { const data = JSON.parse(options.body); data.Priority = Number($('#priority')?.value || 0); data.ProxyURL = $('#account-proxy')?.value.trim() || ''; options = { ...options, body: JSON.stringify(data) }; } catch {}
  }
  return apiFetch(url, options);
};
const apiKeyLabel = $('#api-key').closest('label');
const nameLabel = $('#name').closest('label');
const workspaceLabel = $('#workspace-id').closest('label');
const cookieLabel = $('#auth-cookie').closest('label');
$('#modal-description').insertAdjacentHTML('afterend', '<label class="account-mode-field">添加方式<select id="account-add-mode"><option value="workspace">Workspace + Cookie</option><option value="login">账号密码登录</option><option value="api_key">仅 API Key</option></select></label>');
const applyAccountMode = () => { const mode = $('#account-add-mode').value, apiOnly = mode === 'api_key', loginMode = mode === 'login', minimal = apiOnly && !editingID; nameLabel.hidden = minimal || loginMode; workspaceLabel.hidden = apiOnly || loginMode; cookieLabel.hidden = apiOnly || loginMode; apiKeyLabel.hidden = loginMode; $('#login-account-fields').hidden = !loginMode; $('.gateway-account-fields').hidden = false; $('.credential-help').hidden = apiOnly; $('#discovery-result').hidden = apiOnly; $('#modal-description').textContent = minimal ? '填写 API Key，程序会自动同时探测 Go 和 Zen 权益并尝试提取 Workspace ID。' : loginMode ? '后台执行 GitHub OAuth 协议登录，自动取得 Workspace、Cookie、邮箱和本人 API Key。' : apiOnly ? '编辑 API Key-only 凭证的显示名称、调度和代理配置。' : '填写 Workspace ID 和 Cookie，程序会自动读取邮箱与 API Key。'; $('#api-key-hint').textContent = apiOnly ? (editingID ? '留空则保留当前 Key' : '必填，将自动探测 Go 和 Zen') : '可选，留空自动获取'; $('#api-key').placeholder = apiOnly ? '请输入 sk-...' : '自动获取，或手动填写'; if (!editingID) $('#save').textContent = loginMode ? (loginExtractionComplete ? '确认并保存' : '登录并获取') : apiOnly ? '保存 API Key' : (discoveryComplete ? '确认并保存' : '自动识别账号'); };
$('#account-add-mode').onchange = applyAccountMode;
apiKeyLabel.insertAdjacentHTML('afterend', '<div class="credential-grid gateway-account-fields"><label>优先级 <small>默认 0，数字越小越优先</small><input id="priority" type="number" value="0"></label><label>独立代理 <small>优先于全局代理</small><input id="account-proxy" placeholder="http://127.0.0.1:7890"></label></div>');
document.addEventListener('click', e => { const edit = e.target.closest('[data-edit]'); if (edit) { const a = accounts.find(x => x.id === edit.dataset.edit); if (a) { $('#priority').value = a.priority || 0; $('#account-proxy').value = a.proxyUrl || ''; } } });
$$('.add-btn').forEach(b => b.addEventListener('click', () => { $('#priority').value = 0; $('#account-proxy').value = ''; $('#account-add-mode').value = 'workspace'; ['#login-account', '#login-account-password', '#login-email-password'].forEach(x => $(x).value = ''); applyAccountMode(); }));
document.addEventListener('click', e => { const edit = e.target.closest('[data-edit]'); if (!edit) return; const a = accounts.find(x => x.id === edit.dataset.edit); if (!a) return; $('#account-add-mode').value = a.apiOnly ? 'api_key' : 'workspace'; applyAccountMode(); });

$('#save').addEventListener('click', async e => { if ($('#account-add-mode').value !== 'api_key') return; e.preventDefault(); e.stopImmediatePropagation(); const button = $('#save'), apiKey = $('#api-key').value.trim(); if (!apiKey && !editingID) { toast('请填写 API Key'); return; } const existing = editingID ? accounts.find(x => x.id === editingID) : null; const payload = { Name: $('#name').value.trim(), WorkspaceID: existing?.workspaceId || '', APIKey: apiKey, APIOnly: true, Priority: Number($('#priority').value || 0), ProxyURL: $('#account-proxy').value.trim() }; button.disabled = true; button.textContent = editingID ? '正在保存…' : '正在探测 Go 与 Zen…'; try { const url = editingID ? '/api/accounts/' + encodeURIComponent(editingID) : '/api/accounts'; const saved = await api(url, { method: editingID ? 'PUT' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); $('#modal').classList.remove('open'); editingID = null; await load(); toast(saved.workspaceId ? `已识别 Workspace：${saved.workspaceId}` : 'API Key-only 凭证已保存，Workspace 暂未识别'); } catch (error) { toast(error.message); } finally { button.disabled = false; button.textContent = editingID ? '保存并重新检测' : '保存 API Key'; } }, true);
$('#save').addEventListener('click', async e => { if ($('#account-add-mode').value !== 'login' || loginExtractionComplete) return; e.preventDefault(); e.stopImmediatePropagation(); const account = $('#login-account').value.trim(), password = $('#login-account-password').value, emailPassword = $('#login-email-password').value; if (!account || !password) { toast('请填写 GitHub 账号和密码'); return; } const button = $('#save'); button.disabled = true; button.textContent = '正在协议登录…'; try { const data = await api('/api/accounts/login-extract', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ account, password, emailPassword }) }); $('#workspace-id').value = data.workspaceId || ''; $('#auth-cookie').value = data.authCookie || ''; if (data.email || data.account) $('#name').value = data.email || data.account; renderDiscovery(data); discoveryComplete = true; loginExtractionComplete = true; $('#login-account-password').value = ''; $('#login-email-password').value = ''; button.textContent = '确认并保存'; toast('登录信息已取得，请确认 API Key 后保存'); } catch (error) { toast(error.message); button.textContent = '重新登录获取'; } finally { button.disabled = false; } }, true);

const settingsBody = $('#view-settings .form-body');
$('#view-settings .panel-head h2').textContent = '系统设置';
$('#view-settings .panel-head p').textContent = '网关运行、界面偏好与管理安全';
settingsBody.insertAdjacentHTML('afterbegin', '<section class="credential-settings gateway-settings"><div><h3>API 转发网关</h3><p>配置轮询或优先级故障转移；凭证独立代理优先于全局代理。</p></div><div class="credential-grid"><label>调度模式<select id="gateway-mode"><option value="round_robin">负载均衡（轮询）</option><option value="priority">优先级模式</option></select></label><label>最大尝试次数 <small>0 表示尝试全部凭证</small><input id="retry-limit" type="number" min="0" value="0"></label></div><label>全局代理 <small>支持 HTTP/HTTPS/SOCKS5</small><input id="global-proxy" placeholder="http://127.0.0.1:7890"></label><button class="primary" id="save-gateway">保存网关设置</button></section>');
const settingsChildren = [...settingsBody.children];
const settingsWorkspace = document.createElement('div');
settingsWorkspace.className = 'settings-workspace';
const gatewayColumn = document.createElement('div');
gatewayColumn.className = 'settings-column gateway-column';
const securityColumn = document.createElement('div');
securityColumn.className = 'settings-column security-column';
settingsChildren.slice(0, 4).forEach(node => gatewayColumn.appendChild(node));
settingsChildren.slice(4).forEach(node => securityColumn.appendChild(node));
settingsWorkspace.append(gatewayColumn, securityColumn);
settingsBody.appendChild(settingsWorkspace);
async function loadGateway() { try { const x = await api('/api/settings'); $('#gateway-mode').value = x.mode; $('#retry-limit').value = x.retryLimit; $('#global-proxy').value = x.globalProxy || ''; } catch(e) { toast(e.message); } }
$('#save-gateway').onclick = async () => { try { await api('/api/settings', { method:'PUT', headers:{'Content-Type':'application/json'}, body:JSON.stringify({ mode:$('#gateway-mode').value, retryLimit:Number($('#retry-limit').value || 0), globalProxy:$('#global-proxy').value.trim() }) }); toast('网关设置已热更新'); } catch(e) { toast(e.message); } };

async function loadLogs() { try { const data = await api('/api/logs?limit=300'); const rows = Array.isArray(data) ? data : []; $('#log-list').innerHTML = rows.length ? rows.map(x => `<tr><td>${new Date(x.time).toLocaleString('zh-CN')}</td><td><code>${escapeHTML(x.route)}</code><small>${escapeHTML(x.model || '—')}</small></td><td>${escapeHTML(x.credentialName || '—')}<small>第 ${x.attempt} 次</small></td><td><b class="http-status ${x.statusCode >= 400 ? 'bad' : ''}">${x.statusCode || '网络错误'}</b></td><td>${x.inputTokens || 0} / ${x.outputTokens || 0}</td><td>${x.cacheRead || 0} / ${x.cacheWrite || 0}</td><td>${formatDuration(x.durationMs)}</td><td>${x.errorBody ? `<details><summary>查看</summary><pre>${escapeHTML(x.errorBody)}</pre></details>` : '—'}</td></tr>`).join('') : '<tr><td colspan="8" class="empty">暂无转发请求</td></tr>'; } catch(e) { toast(e.message); } }
$('#refresh-logs').onclick = loadLogs;
$('#clear-logs').onclick = async () => { if(confirm('确认清空请求日志？')) { await api('/api/logs',{method:'DELETE'}); loadLogs(); } };
async function loadTokens() { try { const data = await api('/api/tokens'); const rows = Array.isArray(data) ? data : []; $('#token-list').innerHTML = rows.length ? rows.map(x => `<div class="token-row"><div><b>${escapeHTML(x.name)}</b><code>${escapeHTML(x.prefix)}••••••</code><small>创建 ${new Date(x.createdAt).toLocaleString('zh-CN')} · ${x.lastUsed && !x.lastUsed.startsWith('0001-') ? '最近使用 '+new Date(x.lastUsed).toLocaleString('zh-CN') : '尚未使用'}</small></div><div class="actions"><button class="secondary" data-token-toggle="${x.id}" data-enabled="${x.enabled}">${x.enabled ? '停用' : '启用'}</button><button class="danger-button" data-token-delete="${x.id}">删除</button></div></div>`).join('') : '<div class="empty">还没有访问令牌</div>'; $$('[data-token-toggle]').forEach(b => b.onclick=async()=>{await api('/api/tokens/'+b.dataset.tokenToggle,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled:b.dataset.enabled!=='true'})});loadTokens()}); $$('[data-token-delete]').forEach(b=>b.onclick=async()=>{if(confirm('确认删除此令牌？')){await api('/api/tokens/'+b.dataset.tokenDelete,{method:'DELETE'});loadTokens()}}); } catch(e) { toast(e.message); } }
$('#create-token').onclick = async () => { const name = prompt('请输入令牌名称'); if (!name) return; try { const x=await api('/api/tokens',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name})}); prompt('令牌只显示这一次，请立即保存：',x.token); loadTokens(); } catch(e){toast(e.message)} };
const originalOpenView = openView; openView = n => { originalOpenView(n); if(n==='logs') loadLogs(); if(n==='tokens') loadTokens(); if(n==='settings') loadGateway(); };
const initial = location.hash.slice(1); if (['overview', 'accounts', 'logs', 'tokens', 'rules', 'settings'].includes(initial)) openView(initial); load(); loadVersion();
