let accounts = [], currentFilter = 'all', poolFilter = 'all', editingID = null, modelCatalog = { go: { models: [], error: '' }, zen: { models: [], error: '' } }, activeModelType = 'go';
const $ = s => document.querySelector(s), $$ = s => document.querySelectorAll(s);
const windows = a => [a.rolling, a.weekly, a.monthly].filter(Boolean);
const maxUsage = a => windows(a).length ? Math.max(...windows(a).map(x => x.usagePercent)) : 0;
const statusText = s => s === 'healthy' ? '运行正常' : s === 'warning' ? '接近阈值' : s === 'critical' ? '用量告急' : s === 'checking' ? '检查中' : '连接失败';
const statusClass = s => ['warning', 'critical', 'error'].includes(s) ? s : 'healthy';
const formatTime = v => v && !v.startsWith('0001-') ? new Date(v).toLocaleString('zh-CN', { month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit' }) : '尚未检查';
const resetText = w => { if (!w) return '无数据'; const sec = Math.max(0, Math.round((new Date(w.resetAt) - Date.now()) / 1000)); if (sec < 60) return '即将重置'; if (sec < 3600) return `${Math.ceil(sec / 60)} 分钟后重置`; if (sec < 86400) return `${Math.ceil(sec / 3600)} 小时后重置`; return `${Math.ceil(sec / 86400)} 天后重置`; };
const money = v => '$' + Number(v || 0).toFixed(2);

async function api(url, options) { const res = await fetch(url, options); if (!res.ok) { let data = {}; try { data = await res.json(); } catch {} throw new Error(data.error || `HTTP ${res.status}`); } if (res.status === 204) return null; return res.json(); }
async function load() { accounts = await api('/api/accounts'); render(); }
async function loadVersion() { try { const info = await api('/api/version'); $('#app-version').textContent = `GoQuota ${info.version}`; } catch {} }

function render() {
  const goCount = accounts.filter(a => a.goAvailable).length, zenCount = accounts.filter(a => a.zenAvailable).length;
  $('#total').textContent = accounts.length; $('#type-summary').textContent = `Go ${goCount} · Zen ${zenCount}`;
  $('#healthy').textContent = accounts.filter(a => a.status === 'healthy').length;
  $('#attention').textContent = accounts.filter(a => !['healthy', 'checking'].includes(a.status)).length;
  $('#zen-cost').textContent = money(accounts.filter(a => a.type === 'zen').reduce((s, a) => s + (a.zenBalance || 0), 0));
  renderOverview(); renderAlerts(); renderPool($('#account-search').value);
}

function usageCard(label, w) { if (!w) return `<div class="usage-window unavailable"><div class="model-line"><span>${label}</span><b>无数据</b></div><div class="bar"></div><small>等待官方数据</small></div>`; const p = Math.round(w.usagePercent); return `<div class="usage-window"><div class="model-line"><span>${label} · $${w.limitUsd}</span><b>${p}%</b></div><div class="bar"><div class="fill ${p >= 90 ? 'danger' : p >= 80 ? 'warn' : ''}" style="width:${Math.min(100, p)}%"></div></div><small>${resetText(w)}</small></div>`; }
function goDetails(a) { return `<div class="models">${usageCard('5 小时', a.rolling)}${usageCard('每周', a.weekly)}${usageCard('每月', a.monthly)}</div>`; }
function zenDetails(a) { if (!a.zenAvailable) return `<div class="account-error service-note">Zen 未检测到：${escapeHTML(a.zenError || '暂无数据')}</div>`; return `<div class="zen-metrics"><div class="zen-metric"><span>Zen 当前余额</span><b>${money(a.zenBalance)}</b></div><div class="zen-metric"><span>计费方式</span><b>按量付费</b></div><div class="zen-metric"><span>状态</span><b>${a.zenBalance > 0 ? '可用' : '余额为零'}</b></div></div>`; }

function renderOverview() {
  const list = accounts.filter(a => currentFilter === 'all' || (currentFilter === 'warning' && ['warning', 'critical'].includes(a.status)) || (currentFilter === 'error' && a.status === 'error'));
  $('#account-list').innerHTML = list.length ? list.map(a => `<div class="account"><div class="account-top"><div class="account-id"><span class="avatar">${a.name.slice(0, 1)}</span><div><div class="account-name">${escapeHTML(a.name)}${a.goAvailable ? '<i class="provider-badge">GO</i>' : ''}${a.zenAvailable ? '<i class="provider-badge zen">ZEN</i>' : ''}</div><div class="account-email">${escapeHTML(a.workspaceId)} · ${a.modelCount || 0} 个模型</div></div></div><div class="status ${statusClass(a.status)}"><i class="dot"></i>${statusText(a.status)}</div></div>${a.error ? `<div class="account-error">${escapeHTML(a.error)}</div>` : ''}<div class="service-title">Go 订阅</div>${a.goAvailable ? goDetails(a) : `<div class="account-error service-note">Go 未开通或无额度窗口</div>`}<div class="service-title">Zen 按量付费</div>${zenDetails(a)}<div class="checked">检查于 ${formatTime(a.lastChecked)}</div></div>`).join('') : '<div class="empty">还没有工作区，添加一次即可自动检测 Go 与 Zen。</div>';
}

function renderAlerts() { const list = accounts.filter(a => ['warning', 'critical', 'error'].includes(a.status)); $('#alert-count').textContent = list.length; $('#alert-list').innerHTML = list.length ? list.map(a => `<div class="alert"><span class="alert-icon ${a.status === 'error' || a.status === 'critical' ? 'red' : ''}">${a.status === 'error' ? '!' : '↗'}</span><div><b>${escapeHTML(a.name)} · ${statusText(a.status)}</b><p>${a.error ? escapeHTML(a.error) : a.goAvailable ? `Go 最高窗口已使用 ${Math.round(maxUsage(a))}%` : `Zen 当前余额 ${money(a.zenBalance)}`}</p><time>${formatTime(a.lastChecked)}</time></div></div>`).join('') : '<div class="empty">暂无真实告警</div>'; }

function quotaMini(label, value) { if (!value) return `<div class="quota-mini muted-quota"><span>${label}</span><b>未开通</b><i></i></div>`; const p = Math.round(value.usagePercent); return `<div class="quota-mini"><span>${label}</span><b>${p}%</b><i><i class="${p >= 90 ? 'danger' : p >= 80 ? 'warn' : ''}" style="width:${Math.min(100, p)}%"></i></i><small>${resetText(value)}</small></div>`; }
function renderPool(q = '') {
  q = q.trim().toLowerCase();
  const list = accounts.filter(a => (!q || a.name.toLowerCase().includes(q) || (a.workspaceId || '').toLowerCase().includes(q)) && (poolFilter === 'all' || (poolFilter === 'healthy' && a.status === 'healthy') || (poolFilter === 'attention' && ['warning', 'critical'].includes(a.status)) || (poolFilter === 'error' && a.status === 'error')));
  $('#pool-count').textContent = `${list.length} 个工作区`;
  $('#pool-list').innerHTML = list.length ? list.map(a => `<article class="pool-card ${statusClass(a.status)}"><div class="pool-card-head"><div class="account-id"><span class="pool-avatar">${a.name.slice(0, 1)}</span><div><div class="pool-card-name">${escapeHTML(a.name)}${a.goAvailable ? '<i class="provider-badge">GO</i>' : ''}${a.zenAvailable ? '<i class="provider-badge zen">ZEN</i>' : ''}</div><div class="pool-workspace">${escapeHTML(a.workspaceId)}</div></div></div><span class="pool-status ${statusClass(a.status)}"><i></i>${statusText(a.status)}</span></div><div class="pool-health"><span>凭证 ${a.hasCookie ? '已配置' : '缺失'}</span><span>Go ${a.goModelCount || 0} · Zen ${a.zenModelCount || 0}</span><time>${formatTime(a.lastChecked)}</time></div>${a.error ? `<div class="account-error">${escapeHTML(a.error)}</div>` : ''}<div class="pool-service"><div class="pool-service-title"><span>Go 订阅额度</span><em>${a.goAvailable ? `最高 ${Math.round(maxUsage(a))}%` : '未开通'}</em></div><div class="quota-mini-grid">${quotaMini('5 小时', a.rolling)}${quotaMini('每周', a.weekly)}${quotaMini('每月', a.monthly)}</div></div><div class="pool-service zen-service"><div class="pool-service-title"><span>Zen 按量付费</span><em>${a.zenAvailable ? '已识别' : '未识别'}</em></div><div class="zen-balance-row"><span>当前余额</span><b>${a.zenAvailable ? money(a.zenBalance) : '—'}</b></div></div><footer class="pool-card-actions"><button class="models-button" data-models="${a.id}">模型</button><button title="立即刷新" data-card-refresh="${a.id}">↻</button><button class="edit-button" data-edit="${a.id}">编辑</button><button class="delete-button" title="删除工作区" data-delete="${a.id}">删除</button></footer></article>`).join('') : '<div class="empty pool-empty">没有匹配的工作区</div>';
  $$('[data-models]').forEach(b => b.onclick = () => openModels(b.dataset.models, b));
  $$('[data-card-refresh]').forEach(b => b.onclick = () => refreshOne(b.dataset.cardRefresh, b));
  $$('[data-edit]').forEach(b => b.onclick = () => openEdit(b.dataset.edit));
  $$('[data-delete]').forEach(b => b.onclick = () => deleteAccount(b.dataset.delete));
}

function escapeHTML(s) { const d = document.createElement('div'); d.textContent = s || ''; return d.innerHTML; }
function toast(m) { const e = $('#toast'); e.textContent = m; e.classList.add('show'); setTimeout(() => e.classList.remove('show'), 2400); }
function openView(n) { $$('.nav-item').forEach(x => x.classList.toggle('active', x.dataset.view === n)); $$('.view').forEach(x => x.classList.toggle('active', x.id === `view-${n}`)); location.hash = n; scrollTo({ top: 0, behavior: 'smooth' }); }
async function refresh(button) { button.textContent = '…'; button.disabled = true; try { accounts = await api('/api/refresh', { method: 'POST' }); render(); $('#sync-time').textContent = '刚刚'; toast('Go 与 Zen 数据已分别刷新'); } catch (e) { toast(e.message); } finally { button.textContent = '↻'; button.disabled = false; } }
async function deleteAccount(id) { if (!confirm('确认删除这个监控项？本机保存的凭证也会被删除。')) return; try { await api('/api/accounts/' + encodeURIComponent(id), { method: 'DELETE' }); await load(); toast('监控项已删除'); } catch (e) { toast(e.message); } }
async function refreshOne(id, button) { button.disabled = true; button.textContent = '…'; try { const updated = await api(`/api/accounts/${encodeURIComponent(id)}/refresh`, { method: 'POST' }); const index = accounts.findIndex(a => a.id === id); if (index >= 0) accounts[index] = updated; render(); toast('工作区已刷新'); } catch (e) { toast(e.message); } finally { button.disabled = false; button.textContent = '↻'; } }
function renderModels(q = '') { q = q.trim().toLowerCase(); const group = modelCatalog[activeModelType] || { models: [], error: '' }; if (group.error) { $('#model-list').innerHTML = `<div class="account-error">${escapeHTML(group.error)}</div>`; return; } const list = (group.models || []).filter(m => !q || m.name.toLowerCase().includes(q) || m.id.toLowerCase().includes(q) || (m.provider || '').toLowerCase().includes(q) || (m.deprecated && ('已弃用'.includes(q) || 'deprecated'.includes(q)))); $('#model-list').innerHTML = list.length ? list.map(m => `<div class="model-item ${m.deprecated ? 'deprecated-model' : ''}"><div><div class="model-name-line"><b>${escapeHTML(m.name)}</b>${m.deprecated ? '<strong>已弃用</strong>' : ''}</div><code>${escapeHTML(m.id)}</code>${m.deprecated ? `<small>弃用日期：${escapeHTML(m.deprecationDate)}</small>` : ''}</div>${m.provider ? `<span>${escapeHTML(m.provider)}</span>` : ''}</div>`).join('') : '<div class="empty">当前分类没有匹配的模型</div>'; }
function selectModelType(type) { activeModelType = type; $$('[data-model-type]').forEach(b => b.classList.toggle('active', b.dataset.modelType === type)); $('#model-search').value = ''; renderModels(); }
async function openModels(id, button) { const account = accounts.find(a => a.id === id); modelCatalog = { go: { models: [], error: '' }, zen: { models: [], error: '' } }; activeModelType = 'go'; $('#model-title').textContent = `${account ? account.name : '账号'} · 可用模型`; $('#model-description').textContent = '正在分别查询 Go 与 Zen 官方模型目录…'; $('#go-model-count').textContent = '—'; $('#zen-model-count').textContent = '—'; $('#model-search').value = ''; $('#model-list').innerHTML = '<div class="model-loading">正在查询…</div>'; $$('[data-model-type]').forEach(b => b.classList.toggle('active', b.dataset.modelType === 'go')); $('#model-modal').classList.add('open'); button.disabled = true; try { const data = await api(`/api/accounts/${encodeURIComponent(id)}/models`); modelCatalog = { go: data.go || { models: [], error: '' }, zen: data.zen || { models: [], error: '' } }; const deprecatedCount = (modelCatalog.zen.models || []).filter(m => m.deprecated).length; $('#go-model-count').textContent = (modelCatalog.go.models || []).length; $('#zen-model-count').textContent = `${(modelCatalog.zen.models || []).length}${deprecatedCount ? ` / ${deprecatedCount} 弃用` : ''}`; $('#model-description').textContent = data.authenticated ? '已使用当前 API Key 分别查询两个官方目录' : '未配置 API Key，分别显示两个公开目录'; renderModels(); } catch (e) { $('#model-description').textContent = '查询失败'; $('#model-list').innerHTML = `<div class="account-error">${escapeHTML(e.message)}</div>`; } finally { button.disabled = false; } }
function openAdd() { editingID = null; $('#modal-title').textContent = '添加工作区'; $('#modal-description').textContent = '添加一次即可自动检测并监控 Go 与 Zen。'; $('#api-key-hint').textContent = '可选，用于读取模型目录'; $('#cookie-hint').textContent = ''; ['#name', '#workspace-id', '#api-key', '#auth-cookie'].forEach(x => $(x).value = ''); $('#save').textContent = '检测并保存'; $('#modal').classList.add('open'); }
function openEdit(id) { const a = accounts.find(x => x.id === id); if (!a) return; editingID = id; $('#modal-title').textContent = '编辑工作区'; $('#modal-description').textContent = '修改后会立即重新检测 Go 与 Zen。'; $('#name').value = a.name; $('#workspace-id').value = a.workspaceId; $('#api-key').value = ''; $('#auth-cookie').value = ''; $('#api-key-hint').textContent = a.hasApiKey ? '留空则保留当前 Key' : '尚未配置，可选'; $('#cookie-hint').textContent = a.hasCookie ? '留空则保留当前 Cookie' : ''; $('#save').textContent = '保存并重新检测'; $('#modal').classList.add('open'); }
$$('.nav-item').forEach(x => x.onclick = () => openView(x.dataset.view)); $$('.add-btn').forEach(x => x.onclick = openAdd); $$('.refresh-btn').forEach(x => x.onclick = () => refresh(x));
$$('.filter').forEach(x => x.onclick = () => { $$('.filter').forEach(y => y.classList.remove('active')); x.classList.add('active'); currentFilter = x.dataset.filter; renderOverview(); });
$('#account-search').oninput = e => renderPool(e.target.value); $('#close').onclick = $('#cancel').onclick = () => $('#modal').classList.remove('open'); $('#modal').onclick = e => { if (e.target.id === 'modal') $('#modal').classList.remove('open'); };
$('#model-search').oninput = e => renderModels(e.target.value); $('#model-close').onclick = () => $('#model-modal').classList.remove('open'); $('#model-modal').onclick = e => { if (e.target.id === 'model-modal') $('#model-modal').classList.remove('open'); };
$$('[data-model-type]').forEach(b => b.onclick = () => selectModelType(b.dataset.modelType));
$$('[data-pool-filter]').forEach(b => b.onclick = () => { $$('[data-pool-filter]').forEach(x => x.classList.remove('active')); b.classList.add('active'); poolFilter = b.dataset.poolFilter; renderPool($('#account-search').value); });
$('#save').onclick = async () => { const button = $('#save'); const payload = { Name: $('#name').value.trim(), WorkspaceID: $('#workspace-id').value.trim(), APIKey: $('#api-key').value.trim(), AuthCookie: $('#auth-cookie').value.trim() }; if (!payload.Name || !payload.WorkspaceID || (!editingID && !payload.AuthCookie)) { toast(editingID ? '请填写名称和 Workspace ID' : '请填写名称、Workspace ID 和 auth Cookie'); return; } button.disabled = true; button.textContent = '正在重新检测…'; try { const url = editingID ? '/api/accounts/' + encodeURIComponent(editingID) : '/api/accounts'; const saved = await api(url, { method: editingID ? 'PUT' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); $('#modal').classList.remove('open'); editingID = null; await load(); toast(saved.status === 'error' ? `已保存，但采集失败：${saved.error}` : '工作区已保存并重新检测'); } catch (e) { toast(e.message); } finally { button.disabled = false; button.textContent = editingID ? '保存并重新检测' : '检测并保存'; } };
['warn', 'danger'].forEach(n => { $(`#${n}-range`).oninput = e => $(`#${n}-value`).textContent = e.target.value + '%'; }); $$('.save-button').forEach(x => x.onclick = () => toast('设置已保存'));
$('#shutdown').onclick = () => $('#confirm').classList.add('open'); $('#shutdown-cancel').onclick = () => $('#confirm').classList.remove('open'); $('#confirm').onclick = e => { if (e.target.id === 'confirm') $('#confirm').classList.remove('open'); }; $('#shutdown-confirm').onclick = async () => { const b = $('#shutdown-confirm'); b.textContent = '正在退出…'; b.disabled = true; try { await fetch('/api/shutdown', { method: 'POST' }); document.body.innerHTML = '<main class="stopped"><div><span class="brand-mark">G</span><h1>GoQuota 已退出</h1><p>本地监控服务已安全关闭。</p></div></main>'; } catch { toast('请在控制台输入 Q 退出'); } };
const initial = location.hash.slice(1); if (['overview', 'accounts', 'rules', 'settings'].includes(initial)) openView(initial); load(); loadVersion();
